/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizprak1;

import javax.swing.JOptionPane;

/**
 *
 * @author WULANDARI
 */
public class kasir extends javax.swing.JFrame {
    String menu;
    private int hargaitem;
    
    public kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        namatoko = new javax.swing.JLabel();
        jeniskopi = new javax.swing.JLabel();
        jmlpesanan = new javax.swing.JLabel();
        kopi = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jmlitem = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        pilihkopi = new javax.swing.JComboBox<>();
        isijumlah = new javax.swing.JTextField();
        panggilkopi = new javax.swing.JTextField();
        panggilharga = new javax.swing.JTextField();
        panggilitem = new javax.swing.JTextField();
        hitungtotal = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        hotice = new javax.swing.JLabel();
        pilihhotice = new javax.swing.JComboBox<>();
        hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        namatoko.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        namatoko.setText("KOPI JANJI MANIS");

        jeniskopi.setText("Jenis Kopi              :");

        jmlpesanan.setText("Jumlah Pesanan   :");

        kopi.setText("Kopi                       :");

        harga.setText("Harga                     :");

        jmlitem.setText("Jumlah Item          :");

        total.setText("Total                      :");

        pilihkopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arabica Coffe", "Robusta Coffe", "Liberian Coffe", "Exelsa Coffe" }));

        isijumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isijumlahActionPerformed(evt);
            }
        });

        panggilitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panggilitemActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        selesai.setText("SELESAI");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        hotice.setText("Hot/Ice                  :");

        pilihhotice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ice", "Hot" }));

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(total)
                                .addGap(19, 19, 19)
                                .addComponent(hitungtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jeniskopi)
                                    .addComponent(jmlpesanan)
                                    .addComponent(hotice)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(kopi)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jmlitem)
                                            .addComponent(harga)
                                            .addComponent(hitung))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(panggilharga)
                                            .addGap(5, 5, 5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(panggilitem, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addGap(6, 6, 6)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(isijumlah)
                                        .addComponent(pilihkopi, 0, 150, Short.MAX_VALUE)
                                        .addComponent(panggilkopi)
                                        .addComponent(pilihhotice, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(hapus)
                        .addGap(18, 18, 18)
                        .addComponent(selesai)
                        .addGap(18, 18, 18)
                        .addComponent(keluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(namatoko)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(namatoko)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jeniskopi)
                    .addComponent(pilihkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isijumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlpesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotice)
                    .addComponent(pilihhotice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga)
                            .addComponent(panggilharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panggilkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kopi))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panggilitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlitem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addComponent(hitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(hitungtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(selesai)
                    .addComponent(keluar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isijumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isijumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isijumlahActionPerformed

    private void panggilitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panggilitemActionPerformed
        // TODO add your handling code here:
        menu = (String) pilihkopi.getSelectedItem();
        int harga = 0;
        menu = (String)pilihkopi.getSelectedItem();
                switch (menu){
                    case "Arabica Coffe" -> {
                        menu = "Arabica Coffe";
                        hargaitem = (int) 20000;
            }
                    case "Robusta Coffe" -> {
                        menu = "Robusta Coffe";
                        hargaitem = (int) 25000;
            }
                    case "Liberian Coffe" -> {
                        menu = "Liberian Coffe";
                        hargaitem = (int) 30000;
            }
                    case "Exelsa Coffe" -> {
                        menu = "Exelsa Coffe";
                        hargaitem = (int) 35000;
            }   
        }
                hargaitem = harga;
    }//GEN-LAST:event_panggilitemActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        pilihkopi.setSelectedItem("");
        isijumlah.setText("");
        pilihhotice.setSelectedItem("");
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        menu = (String) pilihkopi.getSelectedItem();

        switch (menu) {
            case "Arabica Coffee" -> hargaitem = 20000;
            case "Robusta Coffee" -> hargaitem = 25000;
            case "Liberian Coffee" -> hargaitem = 30000;
            case "Exelsa Coffee" -> hargaitem = 35000;
            default -> JOptionPane.showMessageDialog(this, "Pilihan tidak valid.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selesaiActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int hargaitem = Integer.parseInt(panggilharga.getText()); 
        int jumlahPesan = Integer.parseInt(jmlpesanan.getText());
        
        int totalHarga = hargaitem * jumlahPesan;
        
        hitungtotal.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new kasir().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel harga;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField hitungtotal;
    private javax.swing.JLabel hotice;
    private javax.swing.JTextField isijumlah;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jeniskopi;
    private javax.swing.JLabel jmlitem;
    private javax.swing.JLabel jmlpesanan;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel kopi;
    private javax.swing.JLabel namatoko;
    private javax.swing.JTextField panggilharga;
    private javax.swing.JTextField panggilitem;
    private javax.swing.JTextField panggilkopi;
    private javax.swing.JComboBox<String> pilihhotice;
    private javax.swing.JComboBox<String> pilihkopi;
    private javax.swing.JButton selesai;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
